In [1]:
import lzma
import pandas as pd
import pickle

In [8]:
with lzma.open("../../data/cleaned/starling_cleaned.pkl.xz", "rb") as f:
    starling = pickle.load(f)

with lzma.open("../../data/cleaned/unihan_cleaned.pkl.xz", "rb") as f:
    unihan = pickle.load(f)

In [ ]:
merged = unihan.merge(starling, on = "Character", how = "inner")

,kDefinition,Character,kMandarin,kHangul,kKorean,kJapanese,kJapaneseOn,decomposed_hangul,decomposed_pinyin,katakana_romaji,pinyin_without_accent,toneless_pinyin
0,"one; a, an; alone",一,yī,일,IL,イチ,ICHI,"(ㅇ, ㅣ, ㄹ)","(y, i, 1)",ichi,yi,yi
1,"male adult; robust, vigorous; 4th heavenly stem",丁,dīng,정,CENG,チョウ,TEI,"(ㅈ, ㅓ, ㅇ)","(d, ing, 1)",chou,ding,ding
2,seven,七,qī,칠,CHIL,シチ,SHICHI,"(ㅊ, ㅣ, ㄹ)","(q, i, 1)",shichi,qi,qi
3,ten thousand; innumerable,万,wàn,만,MAN,マン,MAN,"(ㅁ, ㅏ, ㄴ)","(w, an, 4)",man,wan,wan
4,"unit of length equal 3.3 meters; gentleman, ma...",丈,zhàng,장,CANG,ジョウ,JOU,"(ㅈ, ㅏ, ㅇ)","(zh, ang, 4)",jou,zhang,zhang
...,...,...,...,...,...,...,...,...,...,...,...,...
7048,turtle or tortoise; cuckold; Kangxi radical 213,龜,guī,구,KWU,キ,KI,"(ㄱ, ㅜ, )","(g, ui, 1)",ki,gui,gui
7049,"autumn, fall; year",龝,qiū,추,CHWU,シュウ,SHUU,"(ㅊ, ㅜ, )","(q, iu, 1)",shuu,qiu,qiu
7050,"flute; pipe, ancient measure; Kangxi radical 214",龠,yuè,약,YAK,ヤク,YAKU,"(ㅇ, ㅑ, ㄱ)","(y, ue, 4)",yaku,yue,yue
7051,"in harmony; calm, peaceful",龢,hé,화,HWA,カ,KA,"(ㅎ, ㅘ, )","(h, e, 2)",ka,he,he
7052,"beg, appeal for help",龥,yù,유,YU,ヤク,YAKU,"(ㅇ, ㅠ, )","(y, u, 4)",yaku,yu,yu

In [7]:
starling

,Character,Modern (Beijing) reading,English meaning,decomposed_pinyin
0,一,yī,"be one, single, whole","(y, i, 1)"
1,乙,yǐ,the 2d of the Heavenly Stems,"(y, i, 3)"
2,丁,dīng,"4th Heavenly Stem; to beat, strike","(d, ing, 1)"
3,七,qī,be seven,"(q, i, 1)"
4,乃,nǎi,"then, and then, now; your (possess.)","(n, ai, 3)"
...,...,...,...,...
5367,虌,biē,an aquatic turtle (Trionyx sinensis),"(b, ie, 1)"
5368,钁,jué,big hoe [Han],"(j, ue, 2)"
5369,驩,huān,= 歡 q. v.,"(h, uan, 1)"
5370,麷,fēng,grain or buds boiled in water,"(f, eng, 1)"
5371,麤,cū,"gross, coarse [LZ]","(c, u, 1)"